FROM node:20-alpine AS builder

WORKDIR /app

# Instalar dependencias gerais e do workspace
COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/

# Rodar o npm install
RUN npm ci

# Copiar os codigos fonte (o dockerignore precisa estar correto)
COPY . .

# Fazer build do web
WORKDIR /app/apps/web
RUN npm run build

# Stage 2 - Nginx
FROM nginx:alpine

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
